language: python
jobs:
  include:
    - python: 3.6
      env: TOXENV=py36
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - python -m pip install pip -U
  - python -m pip install tox
  - python -m pip --version
  - python -m tox --version
script:
  - python -m pip install .
  - python -m pip install -U setuptools wheel
  - python -m tox -e $TOXENV
after_failure:
  - more .tox/log/* | cat
  - more .tox/*/log/* | cat
notifications:
  email:
    on_success: always
    on_failure: always
