github_url = "https://github.com/PyCQA/astroid"

[version]
current = "2.12.0-dev0"
regex = '''
^(?P<major>0|[1-9]\d*)
\.
(?P<minor>0|[1-9]\d*)
\.
(?P<patch>0|[1-9]\d*)
(?:-(?P<prerelease>(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+(?P<buildmetadata>[0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
'''

[git]
message_template = "Bump astroid to {new_version}, update changelog"
tag_template = "v{new_version}"

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[file]]
src = "astroid/__pkginfo__.py"

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made
[[before_commit]]
name = "Upgrade changelog changelog"
cmd = "python3 script/bump_changelog.py {new_version}"

[[before_commit]]
# We only need this during tbump, it's not compatible with python < 3.7
name = "Install dependencie for contributors.txt's update."
cmd = "pip install 'contributors-txt>=0.7.3'"

[[before_commit]]
name = "Normalize the contributors-txt configuration"
cmd = "contributors-txt-normalize-configuration -a script/.contributors_aliases.json -o script/.contributors_aliases.json"

[[before_commit]]
name = "Upgrade the contributors list"
cmd = "python3 script/create_contributor_list.py"

[[before_commit]]
name = "Apply pre-commit"
cmd = "pre-commit run --all-files||echo 'Hack so this command does not fail'"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[after_push]]
#  name = "publish"
#  cmd = "./publish.sh"
