[tool.towncrier]
version = "4.4.0"
directory = "doc/whatsnew/fragments"
filename = "doc/whatsnew/4/4.4/index.rst"
template = "doc/whatsnew/fragments/_template.rst"
issue_format = "`#{issue} <https://github.com/pylint-dev/astroid/issues/{issue}>`_"
wrap = false  # doesn't wrap links correctly if beginning with indentation

# Definition of fragment types.
# We want the changelog to show in the same order as the fragment types
# are defined here. Therefore we have to use the array-style fragment definition.
# The table-style definition, although more concise, would be sorted alphabetically.
# https://github.com/twisted/towncrier/issues/437
[[tool.towncrier.type]]
directory = "breaking"
name = "Breaking Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "user_action"
name = "Changes requiring user actions"
showcontent = true

[[tool.towncrier.type]]
directory = "feature"
name = "New Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "other"
name = "Other Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "Internal Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "performance"
name = "Performance Improvements"
showcontent = true
