#! /bin/sh -e
#


touch /usr/lib/site-python/logilab/__init__.py


# precompile python files
VERSION=2.3
PACKAGEDIR=/usr/lib/site-python/logilab/astng
case "$1" in
    configure|abort-upgrade|abort-remove|abort-deconfigure)
	python$VERSION -O /usr/lib/python$VERSION/compileall.py -q $PACKAGEDIR
	python$VERSION /usr/lib/python$VERSION/compileall.py -q $PACKAGEDIR
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
